export const USER_LOGIN_DETAIL_SUCCESS = 'USER_LOGIN_DETAIL_SUCCESS';
export const PLANET_DETAIL_SUCCESS = "PLANET_DETAIL_SUCCESS";
export const PLANET_SINGLE_DETAIL_SUCCESS = "PLANET_SINGLE_DETAIL_SUCCESS";